import { ProductIntelligence, SpecRow } from "./types";

// Pre-built sample records for demo seeding. These don't call Groq at all —
// they exist so the catalog dashboard is never empty when a judge first
// loads it, and so the demo doesn't depend on Groq being reachable/under
// rate limits at the exact moment you're presenting.

function spec(
  attribute: string,
  value: string,
  unit: string | undefined,
  confidence: number,
  source: SpecRow["source"],
  sourceDetail: string
): SpecRow {
  return { attribute, value, unit, confidence, source, sourceDetail };
}

function minutesAgo(mins: number) {
  return new Date(Date.now() - mins * 60_000).toISOString();
}

function makeProduct(p: {
  minsAgo: number;
  title: string;
  category: string;
  short: string;
  long: string;
  specs: SpecRow[];
  flags?: ProductIntelligence["flags"];
}): ProductIntelligence {
  const createdAt = minutesAgo(p.minsAgo);
  const avgConfidence = p.specs.reduce((s, f) => s + f.confidence, 0) / p.specs.length;
  const completeness = Math.round(Math.min(100, (p.specs.length / 8) * 100));
  const flags = p.flags ?? [];
  const flagPenalty = flags.reduce(
    (acc, f) => acc + (f.severity === "high" ? 15 : f.severity === "medium" ? 8 : 3),
    0
  );
  const qualityScore = Math.max(
    0,
    Math.min(100, Math.round(avgConfidence * 70 + completeness * 0.3 - flagPenalty))
  );
  return {
    id: crypto.randomUUID(),
    createdAt,
    updatedAt: createdAt,
    input: { productName: p.title },
    productTitle: {
      value: p.title,
      confidence: 0.95,
      source: "extracted",
      sourceDetail: "Provided in input"
    },
    category: {
      value: p.category,
      confidence: 0.9,
      source: "extracted",
      sourceDetail: "Stated in source material"
    },
    shortDescription: {
      value: p.short,
      confidence: 0.75,
      source: "inferred",
      sourceDetail: "Generated by enrichment agent"
    },
    longDescription: {
      value: p.long,
      confidence: 0.75,
      source: "inferred",
      sourceDetail: "Generated by enrichment agent"
    },
    specifications: p.specs,
    flags,
    qualityScore,
    completeness,
    status: flags.some((f) => f.severity === "high") || completeness < 50 ? "needs_review" : "processed"
  };
}

export function buildSeedProducts(): ProductIntelligence[] {
  return [
    makeProduct({
      minsAgo: 5,
      title: "3-phase induction motor, 5.5kW, IP55",
      category: "Industrial motors — AC induction",
      short: "5.5kW IP55-rated 3-phase induction motor for continuous industrial duty.",
      long: "A foot-mounted 3-phase induction motor rated at 5.5kW, built to IP55 for dust and splash resistance in demanding shop-floor environments. Suited to pumps, fans, and conveyor drives requiring continuous-duty operation.",
      specs: [
        spec("Power rating", "5.5", "kW", 0.95, "extracted", "Stated in product name"),
        spec("IP rating", "IP55", undefined, 0.95, "extracted", "Stated in product name"),
        spec("Phase", "3-phase", undefined, 0.95, "extracted", "Stated in product name"),
        spec("Voltage class", "415V", undefined, 0.88, "validated", "Cross-checked against standard 3-phase industrial supply"),
        spec("Mounting type", "Foot-mounted", undefined, 0.62, "inferred", "Typical for this power class"),
        spec("Frame size", "112M", undefined, 0.58, "inferred", "Typical IEC frame for 5.5kW rating"),
        spec("Insulation class", "F", undefined, 0.6, "inferred", "Standard for industrial-duty motors")
      ]
    }),
    makeProduct({
      minsAgo: 22,
      title: "Heavy-duty ball bearing conveyor roller",
      category: "Material handling — conveyor components",
      short: "50mm galvanized steel conveyor roller rated to 80kg for gravity roller lines.",
      long: "A sealed precision-bearing conveyor roller in galvanized steel, built for gravity roller conveyors handling loads up to 80kg. Hex-axle drive with a 500mm frame width fits standard modular conveyor bays.",
      specs: [
        spec("Diameter", "50", "mm", 0.95, "extracted", "Stated in spec text"),
        spec("Load capacity", "80", "kg", 0.95, "extracted", "Stated in spec text"),
        spec("Material", "Galvanized steel", undefined, 0.95, "extracted", "Stated in spec text"),
        spec("Shaft type", "Hex axle", undefined, 0.95, "extracted", "Stated in spec text"),
        spec("Frame width", "500", "mm", 0.95, "extracted", "Stated in spec text"),
        spec("Bearing type", "Sealed precision ball bearing", undefined, 0.7, "inferred", "Typical for this roller class")
      ]
    }),
    makeProduct({
      minsAgo: 41,
      title: "Single-phase submersible water pump",
      category: "Pumps — submersible",
      short: "0.5HP single-phase submersible pump for domestic and light industrial use.",
      long: "A compact submersible pump for clean-water applications, delivering up to 15m head on a 230V single-phase supply. IP68-rated housing suits continuous submerged operation.",
      specs: [
        spec("Power rating", "0.5", "HP", 0.95, "extracted", "Stated in spec text"),
        spec("Voltage", "230", "V AC", 0.95, "extracted", "Stated in spec text"),
        spec("Max head", "15", "m", 0.95, "extracted", "Stated in spec text"),
        spec("IP rating", "IP68", undefined, 0.95, "extracted", "Stated in spec text"),
        spec("Operating temperature", "400", "°C", 0.3, "extracted", "Stated in spec text — flagged, see below")
      ],
      flags: [
        {
          field: "Operating temperature",
          issue: "400°C is far outside plausible range for a water pump seal/motor assembly",
          severity: "high"
        }
      ]
    }),
    makeProduct({
      minsAgo: 63,
      title: "Double-acting hydraulic cylinder, 100mm bore",
      category: "Hydraulics — cylinders",
      short: "100mm bore double-acting hydraulic cylinder for industrial press applications.",
      long: "A double-acting hydraulic cylinder with a 100mm bore and 250mm stroke, rated for 210 bar working pressure. Chrome-plated rod for wear resistance in continuous-duty press and lift applications.",
      specs: [
        spec("Bore diameter", "100", "mm", 0.95, "extracted", "Stated in product name"),
        spec("Stroke length", "250", "mm", 0.9, "extracted", "Stated in spec text"),
        spec("Working pressure", "210", "bar", 0.65, "inferred", "Typical rating for this bore class"),
        spec("Rod material", "Chrome-plated steel", undefined, 0.6, "inferred", "Standard for industrial cylinders"),
        spec("Action type", "Double-acting", undefined, 0.95, "extracted", "Stated in product name")
      ]
    }),
    makeProduct({
      minsAgo: 88,
      title: "Centrifugal fan blower, 2800 RPM",
      category: "HVAC — fans and blowers",
      short: "High-static centrifugal blower for industrial ventilation and exhaust systems.",
      long: "A backward-curved centrifugal blower rated at 2800 RPM, designed for high-static-pressure ventilation, dust extraction, and process exhaust systems in industrial settings.",
      specs: [
        spec("Rotation speed", "2800", "RPM", 0.95, "extracted", "Stated in product name"),
        spec("Blade type", "Backward-curved", undefined, 0.55, "inferred", "Typical for high-static applications"),
        spec("Motor mounting", "Direct drive", undefined, 0.5, "inferred", "Common configuration for this class"),
        spec("Airflow capacity", "Not specified", undefined, 0.25, "inferred", "Insufficient input to estimate — flagged")
      ],
      flags: [
        { field: "Airflow capacity", issue: "No basis in input to estimate a value with confidence", severity: "medium" }
      ]
    }),
    makeProduct({
      minsAgo: 110,
      title: "Industrial control relay, 24V DC coil",
      category: "Electrical — control components",
      short: "24V DC coil control relay with 2 changeover contacts for panel-mount switching.",
      long: "A DIN-rail mountable control relay with a 24V DC coil and dual changeover contacts, rated for general-purpose switching in industrial control panels and automation circuits.",
      specs: [
        spec("Coil voltage", "24", "V DC", 0.95, "extracted", "Stated in product name"),
        spec("Contact configuration", "2 changeover", undefined, 0.9, "extracted", "Stated in spec text"),
        spec("Mounting", "DIN rail", undefined, 0.65, "inferred", "Standard for this relay class"),
        spec("Contact rating", "10A @ 250V AC", undefined, 0.55, "inferred", "Typical for general-purpose control relays")
      ]
    }),
    makeProduct({
      minsAgo: 135,
      title: "Pneumatic solenoid valve, 1/4 inch NPT",
      category: "Pneumatics — valves",
      short: "5/2-way pneumatic solenoid valve with 1/4 inch NPT ports for automation circuits.",
      long: "A 5/2-way solenoid-actuated pneumatic valve with 1/4 inch NPT ports, suited to double-acting cylinder control in automated production lines. 24V DC coil, manual override included.",
      specs: [
        spec("Port size", "1/4", "inch NPT", 0.95, "extracted", "Stated in product name"),
        spec("Valve configuration", "5/2-way", undefined, 0.6, "inferred", "Typical for double-acting cylinder control"),
        spec("Coil voltage", "24", "V DC", 0.55, "inferred", "Common standard for pneumatic solenoids"),
        spec("Manual override", "Yes", undefined, 0.5, "inferred", "Standard feature on this valve class")
      ]
    }),
    makeProduct({
      minsAgo: 160,
      title: "Variable frequency drive, 7.5kW",
      category: "Electrical — motor drives",
      short: "7.5kW variable frequency drive for AC induction motor speed control.",
      long: "A 7.5kW-rated variable frequency drive for closed-loop or open-loop AC induction motor control, with built-in EMC filtering and Modbus RTU communication for integration into plant automation networks.",
      specs: [
        spec("Power rating", "7.5", "kW", 0.95, "extracted", "Stated in product name"),
        spec("Input supply", "3-phase 415V", undefined, 0.7, "inferred", "Standard for this power class"),
        spec("Communication protocol", "Modbus RTU", undefined, 0.55, "inferred", "Common on industrial VFDs"),
        spec("Control method", "V/f or vector", undefined, 0.5, "inferred", "Standard control options for this drive class")
      ]
    }),
    makeProduct({
      minsAgo: 190,
      title: "Safety light curtain sensor, 4-beam",
      category: "Safety — machine guarding",
      short: "4-beam safety light curtain for point-of-operation machine guarding.",
      long: "A Type 4 safety light curtain with 4 infrared beams, designed for point-of-operation guarding on presses and automated machinery. Category 4 / PLe rated per ISO 13849-1.",
      specs: [
        spec("Beam count", "4", undefined, 0.95, "extracted", "Stated in product name"),
        spec("Safety category", "Category 4 / PLe", undefined, 0.6, "inferred", "Typical for point-of-operation guarding"),
        spec("Detection range", "0-6", "m", 0.5, "inferred", "Common range for this sensor class"),
        spec("Response time", "< 20", "ms", 0.5, "inferred", "Standard for Type 4 light curtains")
      ]
    })
  ];
}
